### ISSUE TITLE
Qwik Preview Link Broken

### ISSUE THREAD

**Issue by matt-unosquare** [wmalarski/qwik-city-movies#17]
The link to view the actual Movies Qwik Preview is broken. Could we get this redeployed and linked accordingly?

![image](https://github.com/wmalarski/qwik-city-movies/assets/126695488/2fd44334-5534-4689-8a82-ed3d4f01a4ae)

[qwik-city-movies-wm.netlify.app](https://qwik-city-movies-wm.netlify.app/)

**Comment by wmalarski** [comment]
Thanks for noticing. I used all my free resources on Netlify. I redeployed the page here https://qwik-city-movies.pages.dev/

**Comment by matt-unosquare** [comment]
you're the best, thank you
